export const WS_EVENTS = {
  // Interceptor -> Server
  ACTION_EVENT: 'ACTION_EVENT',
  SNAPSHOT_CREATED: 'SNAPSHOT_CREATED',
  PROTECTION_VIOLATION: 'PROTECTION_VIOLATION',
  INTERCEPTOR_HEARTBEAT: 'INTERCEPTOR_HEARTBEAT',
  INTERCEPTOR_STATUS: 'INTERCEPTOR_STATUS',

  // Server -> Interceptor
  COMMAND_STOP: 'COMMAND_STOP',
  COMMAND_CONTINUE: 'COMMAND_CONTINUE',
  ZONE_UPDATE: 'ZONE_UPDATE',
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  ACK: 'ACK',

  // Server -> Dashboard
  EVENT_BROADCAST: 'EVENT_BROADCAST',
  STATE_CHANGE: 'STATE_CHANGE',
  RISK_ALERT: 'RISK_ALERT',
  STATS_UPDATE: 'STATS_UPDATE',
  ZONE_BROADCAST: 'ZONE_BROADCAST',

  // Dashboard -> Server
  COMMAND_RESET: 'COMMAND_RESET',
  COMMAND_ROLLBACK: 'COMMAND_ROLLBACK',
  SUBSCRIBE: 'SUBSCRIBE',
  UNSUBSCRIBE: 'UNSUBSCRIBE',

  // Agent
  AGENT_STATUS_CHANGE: 'AGENT_STATUS_CHANGE',
  AGENT_OUTPUT: 'AGENT_OUTPUT',
  AGENT_ERROR: 'AGENT_ERROR',
  AGENT_LOCATION_UPDATE: 'AGENT_LOCATION_UPDATE',
  AGENT_PLAN_UPDATE: 'AGENT_PLAN_UPDATE',
  AGENT_BREADCRUMB: 'AGENT_BREADCRUMB',
  AGENT_TOKEN_USAGE: 'AGENT_TOKEN_USAGE',

  // Phase Execution
  AGENT_PHASE_UPDATE: 'AGENT_PHASE_UPDATE',

  // Intervention
  AGENT_BREAKPOINT_HIT: 'AGENT_BREAKPOINT_HIT',
  AGENT_BREAKPOINT_SET: 'AGENT_BREAKPOINT_SET',
  AGENT_BREAKPOINT_REMOVED: 'AGENT_BREAKPOINT_REMOVED',
  AGENT_INJECTION_QUEUED: 'AGENT_INJECTION_QUEUED',
  AGENT_INJECTION_APPLIED: 'AGENT_INJECTION_APPLIED',
  AGENT_REDIRECTED: 'AGENT_REDIRECTED',
  AGENT_CHECKPOINT_SAVED: 'AGENT_CHECKPOINT_SAVED',

  // Phase Decision (Dashboard -> Server)
  AGENT_PHASE_APPROVE: 'AGENT_PHASE_APPROVE',
  AGENT_PHASE_REJECT: 'AGENT_PHASE_REJECT',

  // Dev Server
  DEV_SERVER_STATUS: 'DEV_SERVER_STATUS',

  // Simulator
  SIMULATOR_PATCH: 'SIMULATOR_PATCH',
  SIMULATOR_RESYNC: 'SIMULATOR_RESYNC',
  SIMULATOR_SNAPSHOT: 'SIMULATOR_SNAPSHOT',
  SIMULATOR_CONFLICT: 'SIMULATOR_CONFLICT',
} as const;
